apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ai-deployment
spec:
  selector:
    matchLabels:
      app: chatbot-ai
  replicas: 3
  template:
    metadata:
      labels:
        app: chatbot-ai
    spec:
      containers:
        - name: chatbot-ai
          image: itbrainzerfurt/chatbot-ai
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-ai-service
  labels:
    name: chatbot-ai-service
spec:
  type: NodePort
  ports:
    - port: 5000        
      targetPort: 5000  
      nodePort: 30080   
      protocol: TCP
      name: http
  selector:
    app: chatbot-ai
